-- UDTF is a user-defined-table-function
-- This is a function that can return the user a table when they call it

USE DATABASE "MY_TEST_DB" ;
USE SCHEMA "MY_TEST_SCHEMA" ;

CREATE OR REPLACE FUNCTION ALL_OPEN_STORES_IN_NYC()
    RETURNS TABLE (
        STORE_ID INTEGER,
        STORE_NAME VARCHAR,
        EMPLOYEE_COUNT INTEGER,
        "STATE" VARCHAR
    )
AS 
$$
WITH 
-- SELECT ALL OPEN STORES FROM THE MASTER TABLE 
    OPEN_STORES AS (
        SELECT DISTINCT 
            STORE_ID, STORE_NAME, EMPLOYEE_COUNT,
            "OPEN"
        FROM MY_TEST_SCHEMA.STORES_MASTER
        WHERE UPPER("OPEN") = 'Y'
    )
, 
-- USE AN INNER JOIN TO RETAIN ALL OPEN STORES BASED IN `NY` (NEW YORK) STATE 
NY_OPEN_STORES AS (
    SELECT 
        ST.STORE_ID, ST.STORE_NAME, ST.EMPLOYEE_COUNT,
        LOC."STATE"
    FROM 
        OPEN_STORES AS ST 
    INNER JOIN 
        MY_TEST_SCHEMA.STORE_LOCATIONS AS LOC 
    ON 
        ST.STORE_ID = LOC.STORE_ID 
    WHERE 
        LOC."STATE" IN ('NY')  
)
-- RETURN ALL FIELDS FROM THE SELECT INTO THE RESULT OF THIS UDTF 
SELECT * FROM NY_OPEN_STORES 
ORDER BY STORE_ID 
$$
;

-- THIS UDTF CAN BE CALLED BY:
SELECT * FROM TABLE(ALL_OPEN_STORES_IN_NYC()) ;

-- END 