-- create an admin group who have superuser status
CREATE ROLE ADMIN_ROLE WITH SUPERUSER;

-- CREATE READ WRITE ROLE FOR INSERT/UPDATE/DELETE INTO DEV, INSERT/SELECT IN DEV_HISTORY
-- REMOVE TRUNACTE ABILITY 
CREATE ROLE READ_WRITE_ROLE;
GRANT CONNECT ON DATABASE "RULES_REPO" TO READ_WRITE_ROLE;
GRANT USAGE ON SCHEMA DEV TO READ_WRITE_ROLE;
GRANT INSERT, UPDATE, DELETE, SELECT ON ALL TABLES IN SCHEMA DEV TO READ_WRITE_ROLE;
GRANT USAGE ON SCHEMA DEV_HISTORY TO READ_WRITE_ROLE;
GRANT INSERT, SELECT ON ALL TABLES IN SCHEMA DEV_HISTORY TO READ_WRITE_ROLE;
REVOKE TRUNACTE ON ALL TABLES IN SCHEMA DEV FROM READ_WRITE_ROLE;
REVOKE TRUNACTE ON ALL TABLES IN SCHEMA DEV_HISTORY FROM READ_WRITE_ROLE;

-- CREATE READ ONLY ROLE 
CREATE ROLE READ_ONLY_ROLE;
GRANT CONNECT ON DATABASE "RULES_REPO" TO READ_ONLY_ROLE;
GRANT USAGE ON SCHEMA DEV TO READ_ONLY_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DEV TO READ_ONLY_ROLE;
GRANT USAGE ON SCHEMA DEV_HISTORY TO READ_ONLY_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA DEV_HISTORY TO READ_ONLY_ROLE;
REVOKE TRUNACTE ON ALL TABLES IN SCHEMA DEV FROM READ_ONLY_ROLE;
REVOKE TRUNACTE ON ALL TABLES IN SCHEMA DEV_HISTORY FROM READ_ONLY_ROLE;
